import { FC, useState } from "react";
import { FormLabel, Paper, Stack, Typography } from "@mui/material";
import { devCollapsed, devUnCollapsed, primaryBtn } from "../../styles";
import { TextBoxComponent } from "../inputComponents/TextBoxComponent";
import { FormControlComponent } from "../inputComponents/FormControlComponent";
import { FormLabelComponent } from "../inputComponents/FormLabelComponent";
import { ButtonComponent } from "../inputComponents/ButtonComponent";
import { Box } from "@mui/system";

export const AutoGenerated: FC = () => {
  const [collapse, setCollapse] = useState(true);
  const [basic, setBasic] = useState(null);
  const [values, setValues] = useState([0, 0, 0, 0]);

  const onChange = () =>
    setValues(() => {
      return basic
        ? [basic * 5, basic * 20, basic * 4, basic * 20 * 12]
        : [0, 0, 0, 0];
    });
  return (
    <Paper>
      <div style={collapse ? devCollapsed : devUnCollapsed}>
        <Typography variant="h5" p={1} onClick={() => setCollapse(!collapse)}>
          Auto Generated Fields
        </Typography>
        <Box m={2}>
          <br />
          <br />
          <FormControlComponent>
            <FormLabel>Daily Salary Amount</FormLabel>

            <FormLabelComponent
              children={
                <TextBoxComponent
                  variant="outlined"
                  placeholder="Daily Amount"
                  value={basic}
                  onChange={(e: any) => setBasic(e.target.value)}
                />
              }
            />

            <br />
            <Box>
              <ButtonComponent
                title="Calculate"
                // sx="test"
                // variant="contained"
                onClick={onChange}
                className="test"
              />
            </Box>

            <br />
            <Stack direction="row" spacing={2}>
              <FormLabelComponent
                children={
                  <TextBoxComponent
                    variant="outlined"
                    value={values[0]}
                    label="Weekly"
                  />
                }
              />
              <FormLabelComponent
                children={
                  <TextBoxComponent
                    variant="outlined"
                    value={values[1]}
                    label="Monthly"
                  />
                }
              />
              <FormLabelComponent
                children={
                  <TextBoxComponent
                    variant="outlined"
                    value={values[2]}
                    label="Quatrely"
                  />
                }
              />
              <FormLabelComponent
                children={
                  <TextBoxComponent
                    variant="outlined"
                    // disabled
                    value={values[3]}
                    label="Annualy"
                  />
                }
              />
            </Stack>
          </FormControlComponent>
          <br />
        </Box>
      </div>
    </Paper>
  );
};
